### ISSUE TITLE
Crash on Multiplayer bq_admin complete

### ISSUE THREAD

**Issue by estranged42** [Funwayguy/BetterQuesting#129]
Crashed the client and server while testing out new quests in Multiplayer.

MC Version 1.10.2
Forge 12.18.3.2185
BetterQuesting-2.3.207
StandardExpansion-2.3.122

    [08:43:08] [Server thread/WARN]: Couldn't process command: 'bq_admin complete 9'
    java.lang.NullPointerException
            at betterquesting.misc.UserEntry.writeToJson(UserEntry.java:47) ~[UserEntry.class:?]
            at betterquesting.questing.QuestInstance.writeToJson_Progress(QuestInstance.java:936) ~[QuestInstance.class:?]
            at betterquesting.questing.QuestInstance.writeToJson(QuestInstance.java:862) ~[QuestInstance.class:?]
            at betterquesting.questing.QuestInstance.writeToJson(QuestInstance.java:50) ~[QuestInstance.class:?]
            at betterquesting.questing.QuestDatabase.writeToJson_Progress(QuestDatabase.java:224) ~[QuestDatabase.class:?]
            at betterquesting.questing.QuestDatabase.writeToJson(QuestDatabase.java:157) ~[QuestDatabase.class:?]
            at betterquesting.questing.QuestDatabase.getSyncPacket(QuestDatabase.java:134) ~[QuestDatabase.class:?]
            at betterquesting.commands.admin.QuestCommandComplete.runCommand(QuestCommandComplete.java:100) ~[QuestCommandComplete.class:?]
            at betterquesting.commands.BQ_CommandAdmin.func_184881_a(BQ_CommandAdmin.java:112) ~[BQ_CommandAdmin.class:?]
            at net.minecraft.command.CommandHandler.func_175786_a(CommandHandler.java:104) [k.class:?]
            at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:83) [k.class:?]
            at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:913) [me.class:?]
            at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:892) [me.class:?]
            at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [im.class:?]
            at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [im.class:?]
            at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [fl$1.class:?]
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_111]
            at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_111]
            at net.minecraft.util.Util.func_181617_a(SourceFile:45) [h.class:?]
            at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
            at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
            at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
            at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
            at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]

**Comment by GWSheridan** [comment]
Also get this crash as well

**Comment by Funwayguy** [comment]
Seems I made a dumb oversight. Already fixed it up for next update
