### ISSUE TITLE
Crash with 1.9 Forge 1858 BQ Version 1.2.75

### ISSUE THREAD

**Issue by Tedyhere** [Funwayguy/BetterQuesting#20]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPlugin (NoNausea-MC1.9-1.0.jar)
  LoadingPlugin (Quark-beta-13.jar)
  LoadingPlugin (FastLeafDecay-MC1.9-1.2.jar)
  Reborn Core ASM (RebornCore-1.9-2.0.4.46-universal.jar)
Contact their authors BEFORE contacting forge

// This is a token for 1 free hug. Redeem at your nearest Mojangsta: [~~HUG~~]

Time: 4/7/16 10:25 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderException: java.lang.NoClassDefFoundError: net/minecraftforge/event/entity/player/EntityInteractEvent
    at net.minecraftforge.fml.common.LoadController.transition(LoadController.java:179)
    at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:559)
    at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:240)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:434)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:346)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: net/minecraftforge/event/entity/player/EntityInteractEvent
    at java.lang.Class.getDeclaredMethods0(Native Method)
    at java.lang.Class.privateGetDeclaredMethods(Class.java:2693)
    at java.lang.Class.privateGetPublicMethods(Class.java:2894)
    at java.lang.Class.getMethods(Class.java:1607)
    at net.minecraftforge.fml.common.eventhandler.EventBus.register(EventBus.java:60)
    at betterquesting.core.proxies.CommonProxy.registerHandlers(CommonProxy.java:29)
    at betterquesting.core.proxies.ClientProxy.registerHandlers(ClientProxy.java:44)
    at betterquesting.core.BetterQuesting.preInit(BetterQuesting.java:82)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:560)
    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:228)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:206)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
    at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:556)
    ... 10 more
Caused by: java.lang.ClassNotFoundException: net.minecraftforge.event.entity.player.EntityInteractEvent
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 44 more
Caused by: java.lang.NullPointerException
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
    ... 46 more
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.9
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 1260673016 bytes (1202 MB) / 1953497088 bytes (1863 MB) up to 4772593664 bytes (4551 MB)
    JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx5120m -Xms256m -XX:PermSize=256m
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP 9.23 Powered by Forge 12.16.0.1858 48 mods loaded, 48 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCH mcp{9.19} [Minecraft Coder Pack](minecraft.jar) 
    UCH FML{8.0.99.99} [Forge Mod Loader](forge-1.9-12.16.0.1858-1.9.jar) 
    UCH Forge{12.16.0.1858} [Minecraft Forge](forge-1.9-12.16.0.1858-1.9.jar) 
    UCH Baubles{1.2.0.0} [Baubles](Baubles-1.9-1.2.0.0.jar) 
    UCH bdlib{1.11.0.13} [BD Lib](bdlib-1.11.0.13-mc1.9.jar) 
    UCE betterquesting{1.2.75} [Better Questing](BetterQuesting-1.2.75.jar) 
    UCH JEI{3.2.8.182} [Just Enough Items](jei_1.9-3.2.8.182.jar) 
    UCH BloodMagic{1.9-2.0.0-31} [Blood Magic: Alchemical Wizardry](BloodMagic-1.9-2.0.0-31.jar) 
    UCH bookshelfapi{3.0.4} [Bookshelf](Bookshelf-API-1.9-3.0.4.jar) 
    UCH Chameleon{1.9-2.1.3} [Chameleon](Chameleon-1.9-2.1.3.jar) 
    UCH chisel{@VERSION@} [Chisel](Chisel-MC1.9-0.0.4.13.jar) 
    UCH mcmultipart{1.1.1} [MCMultiPart](MCMultiPart-1.1.1-universal.jar) 
    UCH chiselsandbits{9.13} [Chisels & Bits](chiselsandbits-9.13.jar) 
    UCH craftingharmonics{1.0.1} [Crafting Harmonics](craftingharmonics-1.0.1.jar) 
    UCH craftingtweaks{4.0.2} [Crafting Tweaks](craftingtweaks-mc1.9-4.0.2.jar) 
    UCH endercrop{1.9-1.2-1836} [Ender Crop](endercrop-1.9.1.2-1854.jar) 
    UCH ezstorage{1.0} [EZ Storage](ezstorage-1.9-1.2.1.jar) 
    UCH FastLeaveDecay{1.1} [Fast Leave Decay](FastLeafDecay-MC1.9-1.2.jar) 
    UCH SilentLib{1.0.4} [Silent Lib](SilentLib-1.9-1.0.4-10.jar) 
    UCH FunOres{1.2.2} [Fun Ores](FunOres-1.9-1.2.2-59.jar) 
    UCH pressure{1.3.1.12} [Pressure Pipes](pressure-1.3.1.12-mc1.9.jar) 
    UCH advgenerators{0.9.20.6} [Advanced Generators](generators-0.9.20.6-mc1.9.jar) 
    UCH grapple_hooks{1.0.4} [Grapple Hooks](Grapple Hooks-1.9-1.0.4.jar) 
    UCH HelpFixer{1.3.13} [HelpFixer](HelpFixer-1.9-1.3.13.jar) 
    UCH hopperducts{1.4.7} [Hopper Ducts](hopperducts-mc1.9-1.4.7.jar) 
    UCH IronChest{6.0.132.776} [Iron Chest](ironchest-1.9-6.0.132.776.jar) 
    UCH journeymap{1.9-5.1.6b2} [JourneyMap](journeymap-1.9-5.1.6b2-unlimited.jar) 
    UCH llor{1.0.7-mc1.9} [Light Level Overlay Reloaded](LLOverlayReloaded-1.0.7-mc1.9.jar) 
    UCH Neat{GRADLE:VERSION-GRADLE:BUILD} [Neat](Neat 1.2-5.jar) 
    UCH neotech{3.0.5} [NeoTech](NeoTech-1.9-3.0.5.jar) 
    UCH NoNausea{1.0} [No Nausea](NoNausea-MC1.9-1.0.jar) 
    UCH notenoughwands{1.3.1} [Not Enough Wands](notenoughwands-1.9.0-1.3.1.jar) 
    UCH progressiveautomation{1.6.38} [Progressive Automation](ProgressiveAutomation-1.9-1.6.38.jar) 
    UCH Psi{beta-31} [Psi](Psi-beta-31.jar) 
    UCH reborncore{2.0.4.46} [RebornCore](RebornCore-1.9-2.0.4.46-universal.jar) 
    UCH QuantumStorage{3.0.0} [QuantumStorage](QuantumStorage-1.9-3.0.0.jar) 
    UCH Quark{beta-13} [Quark](Quark-beta-13.jar) 
    UCH rftools{4.23beta40} [RFTools](rftools-1.9.0-4.23beta40.jar) 
    UCH rftoolsdim{4.23beta33} [RFTools Dimensions](rftoolsdim-1.9.0-4.23beta33.jar) 
    UCH routerreborn{1.9-4.0.1.11b_universal} [Router Reborn](RouterReborn-1.9-4.0.1.11b_universal.jar) 
    UCH sciapi{1.3.0.3} [SciAPI](SciAPI-1.3.0.3.jar) 
    UCH SilentGems{2.0.4} [Silent's Gems](SilentsGems-1.9-2.0.4-alpha-18.jar) 
    UCH SimpleGraves{1.9-1.0.0-8} [SimpleGraves](SimpleGraves-1.9-1.0.0-8.jar) 
    UCH soulshardstow{1.9-2.3.8-23} [Soul Shards - The Old Ways](SoulShards-TOW-1.9-2.3.8-23.jar) 
    UCH stellarsky{0.3.2.0} [Stellar Sky](Stellar Sky-0.3.2.0.jar) 
    UCH StorageDrawers{1.9-3.1.4} [Storage Drawers](StorageDrawers-1.9-3.1.4.jar) 
    UCH techreborn{1.0.4.143} [TechReborn](TechReborn-1.9-1.0.4.143-universal.jar) 
    UCH Waila{1.7.0} [Waila](Waila-1.7.0-B2_1.9.jar) 
    Loaded coremods (and transformers): 
LoadingPlugin (NoNausea-MC1.9-1.0.jar)
  lumien.nonausea.asm.ClassTransformer
LoadingPlugin (Quark-beta-13.jar)
  vazkii.quark.base.asm.ClassTransformer
LoadingPlugin (FastLeafDecay-MC1.9-1.2.jar)
  lumien.fastleavedecay.asm.ClassTransformer
Reborn Core ASM (RebornCore-1.9-2.0.4.46-universal.jar)
  reborncore.asm.RebornClassTransformer
    GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 358.91' Renderer: 'GeForce GTX 750/PCIe/SSE2'
    List of loaded APIs: 
        \* Baubles|API (1.1.1.0) from Baubles-1.9-1.2.0.0.jar
        \* BloodMagic|API (@VERSION@) from BloodMagic-1.9-2.0.0-31.jar
        \* ChiselAPI (0.0.1) from Chisel-MC1.9-0.0.4.13.jar
        \* ChiselAPI|Carving (0.0.1) from Chisel-MC1.9-0.0.4.13.jar
        \* ChiselsAndBitsAPI (1.8.1) from chiselsandbits-9.13.jar
        \* CoFHAPI (1.8.9R1.2.0B1) from RouterReborn-1.9-4.0.1.11b_universal.jar
        \* CoFHAPI|block (1.8.9R1.2.0B1) from ProgressiveAutomation-1.9-1.6.38.jar
        \* CoFHAPI|energy (1.8.9R1.2.0B1) from RouterReborn-1.9-4.0.1.11b_universal.jar
        \* CoFHAPI|tileentity (1.8.9R1.2.0B1) from ProgressiveAutomation-1.9-1.6.38.jar
        \* CraftingTweaks|API (4.1) from craftingtweaks-mc1.9-4.0.2.jar
        \* FunOresAPI (3) from FunOres-1.9-1.2.2-59.jar
        \* IC2API (1.0) from RebornCore-1.9-2.0.4.46-universal.jar
        \* journeymap|client-api (1.2-SNAPSHOT) from journeymap-1.9-5.1.6b2-unlimited.jar
        \* journeymap|client-api-display (1.2-SNAPSHOT) from journeymap-1.9-5.1.6b2-unlimited.jar
        \* journeymap|client-api-event (1.2-SNAPSHOT) from journeymap-1.9-5.1.6b2-unlimited.jar
        \* journeymap|client-api-model (1.2-SNAPSHOT) from journeymap-1.9-5.1.6b2-unlimited.jar
        \* journeymap|client-api-util (1.2-SNAPSHOT) from journeymap-1.9-5.1.6b2-unlimited.jar
        \* JustEnoughItemsAPI (3.1.0) from jei_1.9-3.2.8.182.jar
        \* McJtyLib (1.9.0-1.8.1beta14) from mcjtylib-1.9.0-1.8.1beta14.jar
        \* pressureAPI (1.3.1.12) from pressure-1.3.1.12-mc1.9.jar
        \* PsiAPI (2) from Psi-beta-31.jar
        \* reborncoreAPI (2.0.4.46) from RebornCore-1.9-2.0.4.46-universal.jar
        \* SoulShardsTOW|API (0.1.5) from SoulShards-TOW-1.9-2.3.8-23.jar
        \* stellarsky|API (1.4) from Stellar Sky-0.3.2.0.jar
        \* StorageDrawersAPI (1.7.10-1.2.0) from StorageDrawers-1.9-3.1.4.jar
        \* StorageDrawersAPI|config (1.7.10-1.2.0) from StorageDrawers-1.9-3.1.4.jar
        \* StorageDrawersAPI|event (1.7.10-1.2.0) from StorageDrawers-1.9-3.1.4.jar
        \* StorageDrawersAPI|inventory (1.7.10-1.2.0) from StorageDrawers-1.9-3.1.4.jar
        \* StorageDrawersAPI|pack (1.7.10-1.2.0) from StorageDrawers-1.9-3.1.4.jar
        \* StorageDrawersAPI|registry (1.7.10-1.2.0) from StorageDrawers-1.9-3.1.4.jar
        \* StorageDrawersAPI|render (1.7.10-1.2.0) from StorageDrawers-1.9-3.1.4.jar
        \* StorageDrawersAPI|storage (1.7.10-1.2.0) from StorageDrawers-1.9-3.1.4.jar
        \* StorageDrawersAPI|storage-attribute (1.7.10-1.2.0) from StorageDrawers-1.9-3.1.4.jar
        \* techrebornAPI (1.0.4.143) from TechReborn-1.9-1.0.4.143-universal.jar
        \* WailaAPI (1.3) from Waila-1.7.0-B2_1.9.jar

**Comment by Funwayguy** [comment]
Forge keeps changing how events work and it's likely done so again breaking compatability with BetterQuesting yet again whch was last built for 1816. I'm in the process of updating it to build 1854 so fingers crossed that 1858 supports it too.

Edit: Updated workspace to 1859 just to be sure

**Comment by Funwayguy** [comment]
1.2.78 was updated for 1859 so this hopefully should be fixed for now
