### ISSUE TITLE
Quest Book not working on my server.

### ISSUE THREAD

**Issue by Asdoni** [Funwayguy/BetterQuesting#232]
![b03b24b5e76b0ab33ea654ca20ef104f](https://user-images.githubusercontent.com/31376899/29745663-a1e5d266-8ac1-11e7-80b0-3c8f0da0ea4d.png)

online-mode=true

Everything is fine in single player.
I tested it on project ozone 2 and Craft of titan. Same results.

Logs:

```
[00:39:32] [Server thread/INFO]: Starting minecraft server version 1.7.10
[00:39:32] [Server console handler/ERROR]: Exception handling console input
java.io.IOException: Handle non valido
	at java.io.FileInputStream.readBytes(Native Method) ~[?:1.8.0_144]
	at java.io.FileInputStream.read(Unknown Source) ~[?:1.8.0_144]
	at java.io.BufferedInputStream.read1(Unknown Source) ~[?:1.8.0_144]
	at java.io.BufferedInputStream.read(Unknown Source) ~[?:1.8.0_144]
	at sun.nio.cs.StreamDecoder.readBytes(Unknown Source) ~[?:1.8.0_144]
	at sun.nio.cs.StreamDecoder.implRead(Unknown Source) ~[?:1.8.0_144]
	at sun.nio.cs.StreamDecoder.read(Unknown Source) ~[?:1.8.0_144]
	at java.io.InputStreamReader.read(Unknown Source) ~[?:1.8.0_144]
	at java.io.BufferedReader.fill(Unknown Source) ~[?:1.8.0_144]
	at java.io.BufferedReader.readLine(Unknown Source) ~[?:1.8.0_144]
	at java.io.BufferedReader.readLine(Unknown Source) ~[?:1.8.0_144]
	at lv.run(SourceFile:79) [minecraft_server.1.7.10.jar:?]
[00:39:32] [Server thread/INFO]: Loading properties
[00:39:32] [Server thread/INFO]: Default game type: SURVIVAL
[00:39:32] [Server thread/INFO]: Generating keypair
[00:39:32] [Server thread/INFO]: Starting Minecraft server on *:25565
[00:39:32] [Server thread/INFO]: Preparing level "CarmenSandiego"
[00:39:32] [Server thread/INFO]: Preparing start region for level 0
[00:39:33] [Server thread/INFO]: Preparing spawn area: 86%
[00:39:33] [Server thread/INFO]: Done (1,222s)! For help, type "help" or "?"
```

Any fix?

**Comment by EverNife** [comment]
IS there any other mod working on your server?

Because... this is not even the entire log '-'
If it is... is that really a forge-based server ?

**Comment by Asdoni** [comment]
ye. Every other mod is working.

**Comment by EverNife** [comment]
The server started in ```(1,222s)!```

Anyway, can you send us the entire log ?
Paste it on https://hastebin.com/ please

**Comment by Funwayguy** [comment]
~~From what I can tell the mod indeed loads but it seems that it's missing all the questing data. What `QuestDatabase.json` file are you trying to load and from what directory? Is it marked as the default for new worlds?~~

EDIT: Correction below

**Comment by EverNife** [comment]
1 second to load `every other mod` ?
For me he is trying to make a forge mod work on vanilla server '-'

Just to start the forge it takes more time.
Anyway, i will shut my mouth to stop disturbing :D

**Comment by Funwayguy** [comment]
Oh I was looking at the client side only. Now that you point it out, yes that log is of an unmodified vanilla server. As long as you know what you're talking about, I don't mind the help.

@Asdoni Might want to do some research on how to setup a Forge server and make sure everything loads and says so in the _server logs_ (just being able to log into the server doesn't mean they loaded).

**Comment by Asdoni** [comment]
@Funwayguy  idk what i'm doing wrong. but i'm not trying to make a forge mod work on vanilla server xD i just downloaded a couple of ftb server via curse.
