### ISSUE TITLE
[1.10.2] Connection reset by peer - Mod unusable

### ISSUE THREAD

**Issue by Sir-Will** [Funwayguy/BetterQuesting#295]
hey,

BetterQuesting causes the error below getting spammed in the log which kills the server.
```
[18:08:20] [Netty Epoll Server IO #9/WARN] [io.netty.channel.DefaultChannelPipeline]: An exception was thrown by a user handler's exceptionCaught() method while handling the following exception:
java.io.IOException: Error while writev(...): Connection reset by peer
	at io.netty.channel.epoll.Native.$$YJP$$writevAddresses(Native Method) ~[minecraft_server.1.10.2.jar:?]
	at io.netty.channel.epoll.Native.writevAddresses(Native.java) ~[minecraft_server.1.10.2.jar:?]
	at io.netty.channel.epoll.EpollSocketChannel.writeBytesMultiple(EpollSocketChannel.java:184) ~[minecraft_server.1.10.2.jar:?]
	at io.netty.channel.epoll.EpollSocketChannel.doWriteMultiple(EpollSocketChannel.java:364) ~[minecraft_server.1.10.2.jar:?]
	at io.netty.channel.epoll.EpollSocketChannel.doWrite(EpollSocketChannel.java:317) ~[minecraft_server.1.10.2.jar:?]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:707) [minecraft_server.1.10.2.jar:?]
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.epollOutReady(AbstractEpollChannel.java:248) [minecraft_server.1.10.2.jar:?]
	at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe.epollOutReady(EpollSocketChannel.java:623) [minecraft_server.1.10.2.jar:?]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:322) [minecraft_server.1.10.2.jar:?]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:264) [minecraft_server.1.10.2.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [minecraft_server.1.10.2.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
```
I have this issue only on servers with BetterQuesting and after removing the mod on one of the servers this error did no longer show up on that server.

BetterQuesting-2.3.234
StandardExpansion-2.3.131

**Comment by Mrminesheeps** [comment]
I wouldn't expect a reply anytime soon, since the last issue he replied to was this one, way back in october: https://github.com/Funwayguy/BetterQuesting/issues/250

**Comment by Funwayguy** [comment]
_rises from the dead_

Correction: I stopped replying to BQ2 issues because having to go back and fix old code that I'm going to deprecate anyway would just take away from time that could be better spent on BQ3 code. That's on top of me just generally getting tired of telling people that over and over.

**Comment by Mrminesheeps** [comment]
well, Project Ozone Lite is basically unplayable at this point when the mod is installed, because it's spamming the console with nonsense amounts of messages, which also causes serious instability for the server. often times crashes occur.

Also, I never knew you were working on a BQ3, let alone the fact that you told multiple people about it, so sorry about that... lol.
