### ISSUE TITLE
The game crashed whilst rendering screen Error: java.lang.NullPointerException: Rendering screen

### ISSUE THREAD

**Issue by andrewq99** [Funwayguy/BetterQuesting#383]
minecraft Version 1.12.2 BetterQuesting-3.5.256

**Comment by Funwayguy** [comment]
I'm going to need the _full_ crash report to actually diagnose anything. All that title tells me is a screen crashed. Not which one, how or what mods were involved.

**Comment by kreezxil** [comment]
@Funwayguy I've got a crash while rendering screen for this version 3.5.266 and a crash report at https://pastebin.com/rrhmwWpX

**Comment by Funwayguy** [comment]
I've fixed this for the next build but like I mentioned to another user, the database is in mid rewrite so a new build might potentially take a few days.

**Comment by andrewq99** [comment]
her the crash report ---- Minecraft Crash Report ----

WARNING: coremods are present:
Contact their authors BEFORE contacting forge

// Hey, that tickles! Hehehe!

Time: 5/13/18 10:20 PM
Description: Rendering screen

java.lang.NullPointerException: Rendering screen
	at betterquesting.api2.client.gui.panels.PanelLegacyEmbed.drawPanel(PanelLegacyEmbed.java:51)
	at betterquesting.api2.client.gui.panels.CanvasEmpty.drawPanel(CanvasEmpty.java:53)
	at betterquesting.api2.client.gui.panels.CanvasEmpty.drawPanel(CanvasEmpty.java:53)
	at betterquesting.api2.client.gui.panels.CanvasTextured.drawPanel(CanvasTextured.java:27)
	at betterquesting.api2.client.gui.GuiScreenCanvas.drawPanel(GuiScreenCanvas.java:184)
	at betterquesting.client.gui2.GuiQuest.drawPanel(GuiQuest.java:86)
	at betterquesting.api2.client.gui.GuiScreenCanvas.func_73863_a(GuiScreenCanvas.java:111)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:368)
	at sun.reflect.GeneratedMethodAccessor18.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at Reflector.callVoid(Reflector.java:648)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1456)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1117)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at betterquesting.api2.client.gui.panels.PanelLegacyEmbed.drawPanel(PanelLegacyEmbed.java:51)
	at betterquesting.api2.client.gui.panels.CanvasEmpty.drawPanel(CanvasEmpty.java:53)
	at betterquesting.api2.client.gui.panels.CanvasEmpty.drawPanel(CanvasEmpty.java:53)
	at betterquesting.api2.client.gui.panels.CanvasTextured.drawPanel(CanvasTextured.java:27)
	at betterquesting.api2.client.gui.GuiScreenCanvas.drawPanel(GuiScreenCanvas.java:184)
	at betterquesting.client.gui2.GuiQuest.drawPanel(GuiQuest.java:86)
	at betterquesting.api2.client.gui.GuiScreenCanvas.func_73863_a(GuiScreenCanvas.java:111)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:368)
	at sun.reflect.GeneratedMethodAccessor18.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at Reflector.callVoid(Reflector.java:648)

-- Screen render details --
Details:
	Screen name: betterquesting.client.gui2.GuiQuest
	Mouse location: Scaled: (387, 93). Absolute: (1162, 555)
	Screen size: Scaled: (534, 279). Absolute: (1600, 837). Scale factor of 3

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['captain_andrew11'/184, l='MpServer', x=-260.38, y=67.00, z=-93.01]]
	Chunk stats: MultiplayerChunkCache: 41, 41
	Level seed: 0
	Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-184,64,188), Chunk: (at 8,4,12 in -12,11; contains blocks -192,0,176 to -177,255,191), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 19474 game time, 19474 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 6 total; [EntityBat['Bat'/185, l='MpServer', x=-257.25, y=37.10, z=-88.25], EntityItem['item.item.seeds'/201, l='MpServer', x=-263.85, y=63.00, z=-104.88], EntityPlayerSP['captain_andrew11'/184, l='MpServer', x=-260.38, y=67.00, z=-93.01], EntityPig['Pig'/188, l='MpServer', x=-248.47, y=68.00, z=-89.66], EntityPig['Pig'/189, l='MpServer', x=-257.43, y=68.00, z=-85.75], EntityPig['Pig'/190, l='MpServer', x=-254.92, y=68.00, z=-93.78]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2738)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:418)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 513133512 bytes (489 MB) / 1073741824 bytes (1024 MB) up to 1073741824 bytes (1024 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	IntCache: cache: 0, tcache: 0, allocated: 3, tallocated: 100
	FML: MCP 9.42 Powered by Forge 14.23.3.2678 Optifine OptiFine_1.12.2_HD_U_D2 15 mods loaded, 15 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                   | Version       | Source                                        | Signature                                |
	|:--------- |:-------------------- |:------------- |:--------------------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft            | 1.12.2        | minecraft.jar                                 | None                                     |
	| UCHIJAAAA | mcp                  | 9.42          | minecraft.jar                                 | None                                     |
	| UCHIJAAAA | FML                  | 8.0.99.99     | forge-1.12.2-14.23.3.2678.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge                | 14.23.3.2678  | forge-1.12.2-14.23.3.2678.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | betterquesting       | 3.5.256       | BetterQuesting-3.5.256.jar                    | None                                     |
	| UCHIJAAAA | biomesoplenty        | 7.0.1.2387    | BiomesOPlenty-1.12.2-7.0.1.2387-universal.jar | None                                     |
	| UCHIJAAAA | cdm                  | 0.3.1         | cdm-0.3.1-mc1.12.2.jar                        | None                                     |
	| UCHIJAAAA | cfm                  | 4.2.0         | cfm-4.2.0-mc1.12.2.jar                        | None                                     |
	| UCHIJAAAA | cookingforblockheads | 6.3.26        | CookingForBlockheads_1.12.2-6.3.26.jar        | None                                     |
	| UCHIJAAAA | jei                  | 4.9.1.175     | jei_1.12.2-4.9.1.175.jar                      | None                                     |
	| UCHIJAAAA | lightswitch          | 1.1.1         | lightswitch-1.1.1-mc1.12.2.jar                | None                                     |
	| UCHIJAAAA | tumat                | 1.12.x-1.12.0 | TUMAT-1.12.x-1.12.0.jar                       | None                                     |
	| UCHIJAAAA | veinminer            | 0.38.1        | VeinMiner-1.12-0.38.1.639+134fb1e.jar         | None                                     |
	| UCHIJAAAA | veinminermodsupport  | 0.38.1        | VeinMiner-1.12-0.38.1.639+134fb1e.jar         | None                                     |
	| UCHIJAAAA | xaerominimap         | 1.15          | Xaeros_Minimap_1.15_Forge_1.12.jar            | None                                     |

	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'Intel' Version: '4.5.0 - Build 22.20.16.4749' Renderer: 'Intel(R) UHD Graphics 620'
	Launched Version: 1.12.2-forge1.12.2-14.23.3.2678
	LWJGL: 2.9.4
	OpenGL: Intel(R) UHD Graphics 620 GL version 4.5.0 - Build 22.20.16.4749, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_D2
	OptiFine Build: 20180430-132249
	Render Distance Chunks: 2
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.0 - Build 22.20.16.4749
	OpenGlRenderer: Intel(R) UHD Graphics 620
	OpenGlVendor: Intel
	CpuCount: 8
