### ISSUE TITLE
Crash trying to render plant ball from thaumic arcana in the reward/task gui. 

### ISSUE THREAD

**Issue by charlescannon** [Funwayguy/BetterQuesting#499]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  ForgelinPlugin (Forgelin-1.8.0.jar)
  SSLoadingPlugin (SereneSeasons-1.12.2-1.2.6-universal.jar)
  DCLoadingPlugin (DummyCoreUnofficial-2.4.112.4.jar)
  FMLPlugin (albedo-0.1.3.jar)
  AppleCore (AppleCore-mc1.12.2-3.1.4.jar)
  PassableLeavesCore (PassableLeavesCore-1.12.2-1.0.0.jar)
  CTMCorePlugin (CTM-MC1.12.2-0.3.2.20.jar)
Contact their authors BEFORE contacting forge

// Why is it breaking :(

Time: 11/24/18 2:55 AM
Description: Rendering screen

java.lang.NullPointerException: Rendering screen
	at hu.frontrider.arcana.items.PlantBall.func_77624_a(PlantBall.java:73)
	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:707)
	at betterquesting.api2.client.gui.panels.content.PanelItemSlot.setStoredValue(PanelItemSlot.java:45)
	at betterquesting.api2.client.gui.panels.content.PanelItemSlot.setStoredValue(PanelItemSlot.java:17)
	at betterquesting.api2.client.gui.controls.PanelButtonStorage.<init>(PanelButtonStorage.java:14)
	at betterquesting.api2.client.gui.panels.content.PanelItemSlot.<init>(PanelItemSlot.java:28)
	at betterquesting.api2.client.gui.panels.content.PanelItemSlot.<init>(PanelItemSlot.java:23)
	at betterquesting.api2.client.gui.panels.lists.CanvasItemDatabase.addResult(CanvasItemDatabase.java:118)
	at betterquesting.api2.client.gui.panels.lists.CanvasItemDatabase.addResult(CanvasItemDatabase.java:22)
	at betterquesting.api2.client.gui.panels.lists.CanvasSearch.updateResults(CanvasSearch.java:92)
	at betterquesting.api2.client.gui.panels.lists.CanvasSearch.drawPanel(CanvasSearch.java:41)
	at betterquesting.api2.client.gui.panels.CanvasEmpty.drawPanel(CanvasEmpty.java:52)
	at betterquesting.api2.client.gui.panels.CanvasEmpty.drawPanel(CanvasEmpty.java:52)
	at betterquesting.api2.client.gui.panels.CanvasTextured.drawPanel(CanvasTextured.java:27)
	at betterquesting.api2.client.gui.GuiScreenCanvas.drawPanel(GuiScreenCanvas.java:200)
	at betterquesting.api2.client.gui.GuiScreenCanvas.func_73863_a(GuiScreenCanvas.java:115)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:381)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1124)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1118)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at hu.frontrider.arcana.items.PlantBall.func_77624_a(PlantBall.java:73)
	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:707)
	at betterquesting.api2.client.gui.panels.content.PanelItemSlot.setStoredValue(PanelItemSlot.java:45)
	at betterquesting.api2.client.gui.panels.content.PanelItemSlot.setStoredValue(PanelItemSlot.java:17)
	at betterquesting.api2.client.gui.controls.PanelButtonStorage.<init>(PanelButtonStorage.java:14)
	at betterquesting.api2.client.gui.panels.content.PanelItemSlot.<init>(PanelItemSlot.java:28)
	at betterquesting.api2.client.gui.panels.content.PanelItemSlot.<init>(PanelItemSlot.java:23)
	at betterquesting.api2.client.gui.panels.lists.CanvasItemDatabase.addResult(CanvasItemDatabase.java:118)
	at betterquesting.api2.client.gui.panels.lists.CanvasItemDatabase.addResult(CanvasItemDatabase.java:22)
	at betterquesting.api2.client.gui.panels.lists.CanvasSearch.updateResults(CanvasSearch.java:92)
	at betterquesting.api2.client.gui.panels.lists.CanvasSearch.drawPanel(CanvasSearch.java:41)
	at betterquesting.api2.client.gui.panels.CanvasEmpty.drawPanel(CanvasEmpty.java:52)
	at betterquesting.api2.client.gui.panels.CanvasEmpty.drawPanel(CanvasEmpty.java:52)
	at betterquesting.api2.client.gui.panels.CanvasTextured.drawPanel(CanvasTextured.java:27)
	at betterquesting.api2.client.gui.GuiScreenCanvas.drawPanel(GuiScreenCanvas.java:200)
	at betterquesting.api2.client.gui.GuiScreenCanvas.func_73863_a(GuiScreenCanvas.java:115)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:381)

-- Screen render details --
Details:
	Screen name: betterquesting.client.gui2.editors.nbt.GuiItemSelection
	Mouse location: Scaled: (252, 61). Absolute: (755, 584)
	Screen size: Scaled: (456, 256). Absolute: (1366, 768). Scale factor of 3

**Comment by Funwayguy** [comment]
Thaumic Arcana's Plant Ball tooltips are making the assumption that its NBT is never null (default state for items) and makes no such attempt to check before attempting to read from them.

https://github.com/Frontrider/thaumic_arcana/blob/1.12-dev/src/main/java/hu/frontrider/arcana/content/items/PlantBall.java#L73

They also only report their items to their own creative tab and not the search tab so Better Questing by default simply tries to create an empty stack (again, with no tags per default) resulting in this.

https://github.com/Frontrider/thaumic_arcana/blob/1.12-dev/src/main/java/hu/frontrider/arcana/content/items/PlantBall.java#L119

**Comment by charlescannon** [comment]
Ah. Well, I'll pass the information on to them.

Thanks for the heads up.
