### ISSUE TITLE
Client Crash - ArrayIndexOutOfBoundsException: 0

### ISSUE THREAD

**Issue by yaroslav4167** [Funwayguy/BetterQuesting#528]
```java
java.lang.ArrayIndexOutOfBoundsException: 0
    at betterquesting.api2.client.gui.resources.textures.SlideShowTexture.getCurrentFrame(SlideShowTexture.java:46)
    at betterquesting.api2.client.gui.resources.textures.SlideShowTexture.drawTexture(SlideShowTexture.java:21)
    at betterquesting.api2.client.gui.controls.PanelButton.drawPanel(PanelButton.java:176)
    at betterquesting.api2.client.gui.panels.lists.CanvasScrolling.drawPanel(CanvasScrolling.java:280)
    at betterquesting.api2.client.gui.panels.CanvasEmpty.drawPanel(CanvasEmpty.java:52)
    at betterquesting.api2.client.gui.panels.CanvasEmpty.drawPanel(CanvasEmpty.java:52)
    at betterquesting.api2.client.gui.panels.CanvasEmpty.drawPanel(CanvasEmpty.java:52)
    at betterquesting.api2.client.gui.panels.CanvasTextured.drawPanel(CanvasTextured.java:27)
    at betterquesting.api2.client.gui.GuiScreenCanvas.drawPanel(GuiScreenCanvas.java:200)
    at betterquesting.client.gui2.GuiQuest.drawPanel(GuiQuest.java:86)
    at betterquesting.api2.client.gui.GuiScreenCanvas.drawScreen(GuiScreenCanvas.java:115)
    at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)
    at sun.reflect.GeneratedMethodAccessor71.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.optifine.reflect.Reflector.callVoid(Reflector.java:660)
    at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1456)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1119)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3942)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at ru.gravit.launcher.JH8G70dEgd1car4fvMu3mqgd.IPDG6c1y0shJDjZnBWyXahhi(Unknown Source)
    at ru.gravit.launcher.JH8G70dEgd1car4fvMu3mqgd.main(Unknown Source)
```
Full Crash Log: [https://paste.dimdev.org/itajuxidos.rb](https://paste.dimdev.org/itajuxidos.rb)
Such a problem with my friend who plays with me. I have no such problems.
Appears when opening a book.
Server: SpongeForge

**Comment by Funwayguy** [comment]
That's a new one I haven't seen before. Your friend managed to stumble across an edge case where a particular quest had no textures to cycle through on one of its task previews (likely an ore dictionary item). I've fixed that up for the next build but I'll see if there are any more issues that pop up before I send it out.
