### ISSUE TITLE
Failure to load quests

### ISSUE THREAD

**Issue by ghost** [Funwayguy/BetterQuesting#554]
Firstly:

`[22:15:05] [Server thread/WARN] [net.minecraft.command.CommandHandler]: Couldn't process command: bq_admin default load
java.lang.NoClassDefFoundError: net/minecraft/client/gui/GuiScreen
	at bq_standard.tasks.factory.FactoryTaskAdvancement.createNew(FactoryTaskAdvancement.java:24) ~[FactoryTaskAdvancement.class:?]
	at bq_standard.tasks.factory.FactoryTaskAdvancement.createNew(FactoryTaskAdvancement.java:9) ~[FactoryTaskAdvancement.class:?]
	at betterquesting.questing.tasks.TaskRegistry.createTask(TaskRegistry.java:78) ~[TaskRegistry.class:?]
	at betterquesting.questing.tasks.TaskStorage.readFromNBT(TaskStorage.java:54) ~[TaskStorage.class:?]
	at betterquesting.questing.QuestInstance.readFromNBT(QuestInstance.java:698) ~[QuestInstance.class:?]
	at betterquesting.questing.QuestInstance.readFromNBT(QuestInstance.java:47) ~[QuestInstance.class:?]
	at betterquesting.questing.QuestDatabase.readFromNBT(QuestDatabase.java:117) ~[QuestDatabase.class:?]
	at betterquesting.commands.admin.QuestCommandDefaults.runCommand(QuestCommandDefaults.java:102) ~[QuestCommandDefaults.class:?]
	at betterquesting.commands.BQ_CommandAdmin.execute(BQ_CommandAdmin.java:107) ~[BQ_CommandAdmin.class:?]
	at com.feed_the_beast.ftbutilities.ranks.CommandOverride.execute(CommandOverride.java:88) ~[CommandOverride.class:?]
	at net.minecraft.command.CommandHandler.tryExecute(CommandHandler.java:119) [bj.class:?]
	at net.minecraft.command.CommandHandler.executeCommand(CommandHandler.java:91) [bj.class:?]
	at net.minecraft.network.NetHandlerPlayServer.handleSlashCommand(NetHandlerPlayServer.java:960) [pa.class:?]
	at net.minecraft.network.NetHandlerPlayServer.processChatMessage(NetHandlerPlayServer.java:939) [pa.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.processPacket(SourceFile:37) [la.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.processPacket(SourceFile:9) [la.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_191]
	at net.minecraft.util.Util.runTask(SourceFile:529) [h.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397) [nz.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.gui.GuiScreen
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_191]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_191]
	... 25 more`

Secondly, when quests are updated, they don't automatically propagate to players, requiring the default load command to get new quests (when it works anyway).

**Comment by Funwayguy** [comment]
The first one has been fixed but the second one needs to be made into its own issue thread (if it's still happening that is)
