### ISSUE TITLE
NEI/JEI Item lookup support

### ISSUE THREAD

**Issue by Dream-Master** [Funwayguy/BetterQuesting#61]
This is a suggesion from a user using my Modpack.

"Every time when you open a book, it opens not on the last page you were on, but the front page. Because sometimes you open a book 10-20 times per quest, this thing becomes very annoying.

Also right now you are unable to view the recipe of an item that quest requires. Right clicking on it doesn't open NEI and this was very convenient."

https://github.com/GTNewHorizons/NewHorizons/issues/635

**Comment by Funwayguy** [comment]
The book expansion is not one of mine, you'll have to take it up with that developer.

NEI integration was only partially integrated into the Standard Expansion for rewards not yet for tasks. If it isn't too hard to integrate I'll try and get that released soon.

**Comment by Dream-Master** [comment]
Ok thanks. Will report that to the Quest Book Author.
Should i close this ?

**Comment by Funwayguy** [comment]
I'll keep it open to remind me about NEI/JEI support

**Comment by Dream-Master** [comment]
Ok Thanks.

**Comment by Funwayguy** [comment]
Turns out it was fairly simple to add support for it in 1.7.10 so I just sent out a Standard Expansion build for it.

**Comment by Dream-Master** [comment]
nice thanks i will test it.

**Comment by Dream-Master** [comment]
I get this

```
[15:32:46] [Server thread/ERROR] [betterquesting/]: An error has occured while checking BetterQuesting version!
java.io.FileNotFoundException: https://drone.io/github.com/Funwayguy/BetterQuesting/files/version.txt
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source) ~[?:1.8.0_72]
    at sun.net.www.protocol.http.HttpURLConnection.access$200(Unknown Source) ~[?:1.8.0_72]
    at sun.net.www.protocol.http.HttpURLConnection$9.run(Unknown Source) ~[?:1.8.0_72]
    at sun.net.www.protocol.http.HttpURLConnection$9.run(Unknown Source) ~[?:1.8.0_72]
    at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_72]
    at java.security.AccessController.doPrivilegedWithCombiner(Unknown Source) ~[?:1.8.0_72]
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source) ~[?:1.8.0_72]
    at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source) ~[?:1.8.0_72]
    at betterquesting.client.UpdateNotification.getNotification(UpdateNotification.java:128) ~[UpdateNotification.class:?]
    at betterquesting.client.UpdateNotification.getNotification(UpdateNotification.java:140) ~[UpdateNotification.class:?]
    at betterquesting.client.UpdateNotification.onPlayerLogin(UpdateNotification.java:37) [UpdateNotification.class:?]
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_455_UpdateNotification_onPlayerLogin_PlayerLoggedInEvent.invoke(.dynamic) [?:?]
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) [ASMEventHandler.class:?]
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) [EventBus.class:?]
    at cpw.mods.fml.common.FMLCommonHandler.firePlayerLoggedIn(FMLCommonHandler.java:550) [FMLCommonHandler.class:?]
    at net.minecraft.server.management.ServerConfigurationManager.initializeConnectionToPlayer(ServerConfigurationManager.java:180) [oi.class:?]
    at cpw.mods.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:190) [NetworkDispatcher.class:?]
    at cpw.mods.fml.common.network.handshake.NetworkDispatcher.completeHandshake(NetworkDispatcher.java:463) [NetworkDispatcher.class:?]
    at cpw.mods.fml.common.network.internal.HandshakeCompletionHandler.channelRead0(HandshakeCompletionHandler.java:17) [HandshakeCompletionHandler.class:?]
    at cpw.mods.fml.common.network.internal.HandshakeCompletionHandler.channelRead0(HandshakeCompletionHandler.java:11) [HandshakeCompletionHandler.class:?]
    at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) [SimpleChannelInboundHandler.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [MessageToMessageDecoder.class:?]
    at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) [MessageToMessageCodec.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [DefaultChannelPipeline.class:?]
    at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) [EmbeddedChannel.class:?]
    at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186) [bsx.class:?]
    at fastcraft.at.a(F:978) [fastcraft-1.23.jar:?]
    at fastcraft.H.aq(F:36) [fastcraft-1.23.jar:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]
```

**Comment by Funwayguy** [comment]
That isn't a bug (it's to do with where my builds are compiled) nor is it related to this particular issue

**Comment by Dream-Master** [comment]
Sure I know but I thought it was the easiest way to post it here not open up a new issue for it.

**Comment by 4rz0** [comment]
While this is marked as implemented, I noticed that there doesn't seem to be JEI integration in the latest version for MC1.10.
Is this true or did I just miss some config?

**Comment by EverNife** [comment]
Is there a way to disable NEI support on 1.7.10 ?

For exemple, i have one item that can be collectect into 20 differents quests... and i get a lot of pages on NEI...

Soo, its a bit "ugly" to be seem T.T
