### ISSUE TITLE
crashing wanting to do a mission

### ISSUE THREAD

**Issue by XkRill343** [Funwayguy/BetterQuesting#680]
The game crashed whilist updating screen events
Error: jaca.lang.NoClassDefFoundError: mezz/jei/api/recipe/IFocus

---- Minecraft Crash Report ---- 
// My bad. 

Time: 1/8/20 12:15 AM 
Description: Updating screen events 

java.lang.NoClassDefFoundError: mezz/jei/api/recipe/IFocus 
	at bq_standard.tasks.TaskInteractItem.getTaskGui(TaskInteractItem.java:149) 
	at betterquesting.client.gui2.GuiQuest.refreshTaskPanel(GuiQuest.java:333) 
	at betterquesting.client.gui2.GuiQuest.initPanel(GuiQuest.java:175) 
	at betterquesting.api2.client.gui.GuiScreenCanvas.func_73866_w_(GuiScreenCanvas.java:120) 
	at net.minecraft.client.gui.GuiScreen.func_146280_a(GuiScreen.java:478) 
	at net.minecraft.client.Minecraft.func_147108_a(Minecraft.java:1017) 
	at betterquesting.client.gui2.editors.GuiQuestLineAddRemove.onButtonPress(GuiQuestLineAddRemove.java:183) 
	at betterquesting.client.gui2.editors.GuiQuestLineAddRemove.onPanelEvent(GuiQuestLineAddRemove.java:168) 
	at betterquesting.api2.client.gui.events.PEventBroadcaster$$Lambda$303/670015263.accept(Unknown Source) 
	at betterquesting.api2.client.gui.events.PEventEntry.lambda$fire$0(PEventEntry.java:32) 
	at betterquesting.api2.client.gui.events.PEventEntry$$Lambda$302/662376084.accept(Unknown Source) 
	at java.util.ArrayList.forEach(ArrayList.java:1249) 
	at betterquesting.api2.client.gui.events.PEventEntry.fire(PEventEntry.java:32) 
	at betterquesting.api2.client.gui.events.PEventBroadcaster.postEvent(PEventBroadcaster.java:58) 
	at betterquesting.api2.client.gui.controls.PanelButton.onMouseRelease(PanelButton.java:251) 
	at betterquesting.api2.client.gui.panels.lists.CanvasScrolling.onMouseRelease(CanvasScrolling.java:326) 
	at betterquesting.api2.client.gui.panels.CanvasEmpty.onMouseRelease(CanvasEmpty.java:97) 
	at betterquesting.api2.client.gui.panels.CanvasEmpty.onMouseRelease(CanvasEmpty.java:97) 
	at betterquesting.api2.client.gui.GuiScreenCanvas.onMouseRelease(GuiScreenCanvas.java:319) 
	at betterquesting.api2.client.gui.GuiScreenCanvas.func_146274_d(GuiScreenCanvas.java:227) 
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501) 
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1758) 
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1097) 
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397) 
	at net.minecraft.client.main.Main.main(SourceFile:123) 
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) 
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 
	at java.lang.reflect.Method.invoke(Method.java:497) 
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) 
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) 
Caused by: java.lang.ClassNotFoundException: mezz.jei.api.recipe.IFocus 
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) 
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) 
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) 
	... 31 more 
Caused by: java.lang.NullPointerException 

A detailed walkthrough of the error, its code path and all known details is as follows: 
--------------------------------------------------------------------------------------- 

-- Head -- 
Thread: Client thread 
Stacktrace: 
	at bq_standard.tasks.TaskInteractItem.getTaskGui(TaskInteractItem.java:149) 
	at betterquesting.client.gui2.GuiQuest.refreshTaskPanel(GuiQuest.java:333) 
	at betterquesting.client.gui2.GuiQuest.initPanel(GuiQuest.java:175) 
	at betterquesting.api2.client.gui.GuiScreenCanvas.func_73866_w_(GuiScreenCanvas.java:120) 
	at net.minecraft.client.gui.GuiScreen.func_146280_a(GuiScreen.java:478) 
	at net.minecraft.client.Minecraft.func_147108_a(Minecraft.java:1017) 
	at betterquesting.client.gui2.editors.GuiQuestLineAddRemove.onButtonPress(GuiQuestLineAddRemove.java:183) 
	at betterquesting.client.gui2.editors.GuiQuestLineAddRemove.onPanelEvent(GuiQuestLineAddRemove.java:168) 
	at betterquesting.api2.client.gui.events.PEventBroadcaster$$Lambda$303/670015263.accept(Unknown Source) 
	at betterquesting.api2.client.gui.events.PEventEntry.lambda$fire$0(PEventEntry.java:32) 
	at betterquesting.api2.client.gui.events.PEventEntry$$Lambda$302/662376084.accept(Unknown Source) 
	at java.util.ArrayList.forEach(ArrayList.java:1249) 
	at betterquesting.api2.client.gui.events.PEventEntry.fire(PEventEntry.java:32) 
	at betterquesting.api2.client.gui.events.PEventBroadcaster.postEvent(PEventBroadcaster.java:58) 
	at betterquesting.api2.client.gui.controls.PanelButton.onMouseRelease(PanelButton.java:251) 
	at betterquesting.api2.client.gui.panels.lists.CanvasScrolling.onMouseRelease(CanvasScrolling.java:326) 
	at betterquesting.api2.client.gui.panels.CanvasEmpty.onMouseRelease(CanvasEmpty.java:97) 
	at betterquesting.api2.client.gui.panels.CanvasEmpty.onMouseRelease(CanvasEmpty.java:97) 
	at betterquesting.api2.client.gui.GuiScreenCanvas.onMouseRelease(GuiScreenCanvas.java:319) 
	at betterquesting.api2.client.gui.GuiScreenCanvas.func_146274_d(GuiScreenCanvas.java:227) 
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501) 

-- Affected screen -- 
Details: 
	Screen name: betterquesting.client.gui2.GuiQuest

**Comment by Funwayguy** [comment]
What version of the mod are you using?

**Comment by XkRill343** [comment]
3.5.319 of minecraft 1.12.2

**Comment by Funwayguy** [comment]
and what version of Standard Expansion?

**Comment by XkRill343** [comment]
is 3.4.172

Obtener Outlook para Android<https://aka.ms/ghei36>
________________________________

**Comment by Funwayguy** [comment]
Found and fixed for Standard Expansion 3.4.173 when that comes out

**Comment by XkRill343** [comment]
Thanks bro! You are de best

Obtener Outlook para Android<https://aka.ms/ghei36>
________________________________
