### ISSUE TITLE
ArrayIndexOutOfBoundsException: 500

### ISSUE THREAD

**Issue by judgekreep** [Funwayguy/BetterQuesting#682]
I receive this crash log when clicking on any item within the item selection screen (reward, icon, etc).
Occurs with BetterQuesting-3.0.306 (1.7.10). Works fine when I take off the Inventory Pets mod.

java.lang.ArrayIndexOutOfBoundsException: 500
	at com.inventorypets.petCustom.func_77624_a(petCustom.java:554)
	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:525)
	at betterquesting.api2.client.gui.panels.content.PanelItemSlot.setStoredValue(PanelItemSlot.java:57)
	at betterquesting.api2.client.gui.panels.content.PanelItemSlot.setStoredValue(PanelItemSlot.java:21)
	at betterquesting.api2.client.gui.controls.PanelButtonStorage.<init>(PanelButtonStorage.java:14)
	at betterquesting.api2.client.gui.panels.content.PanelItemSlot.<init>(PanelItemSlot.java:40)
	at betterquesting.api2.client.gui.panels.content.PanelItemSlot.<init>(PanelItemSlot.java:30)
	at betterquesting.api2.client.gui.panels.lists.CanvasItemDatabase.addResult(CanvasItemDatabase.java:121)
	at betterquesting.api2.client.gui.panels.lists.CanvasItemDatabase.addResult(CanvasItemDatabase.java:21)
	at betterquesting.api2.client.gui.panels.lists.CanvasSearch.updateResults(CanvasSearch.java:92)
	at betterquesting.api2.client.gui.panels.lists.CanvasSearch.drawPanel(CanvasSearch.java:41)
	at betterquesting.api2.client.gui.panels.CanvasEmpty.drawPanel(CanvasEmpty.java:52)
	at betterquesting.api2.client.gui.panels.CanvasEmpty.drawPanel(CanvasEmpty.java:52)
	at betterquesting.api2.client.gui.panels.CanvasTextured.drawPanel(CanvasTextured.java:27)
	at betterquesting.api2.client.gui.GuiScreenCanvas.drawPanel(GuiScreenCanvas.java:209)
	at betterquesting.api2.client.gui.GuiScreenCanvas.func_73863_a(GuiScreenCanvas.java:124)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1455)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by Funwayguy** [comment]
This appears to be an issue with inventory pet's tootltip handling and not a BQ issue. Unless I decompiled their mod I'm not entirely sure what exactly is the cause and it wouldn't be up to me to fix anyway.

**Comment by judgekreep** [comment]
I downgraded to BetterQuesting-2.0.233 and there's no problem.
If I update to the latest version, however, I receive a crash log.
It's reasonable to assume that something in the update is causing the problem - and I say assume because I don't have enough information to make any claims.

Nevertheless, I will post the bug on their issue tracker - I was hoping to have some luck here due to the reasoning above and because their Git appears inactive.

**Comment by Funwayguy** [comment]
Just forewarning, there is a massive difference in how 2.x.xxx and 3.x.xxx builds operate including data format. I wouldn't recommend bouncing between them unless you're using backups.

If I had to guess, I'd say the crash has something to do with the pet not being in any inventory which messed thing up with the tooltip query. I suspect it could still crash in 2.x.xxx given the right conditions when you hover over the pet item.
